Add support for writing group systems
olivere/bmecat pull request #5
Opened 2020-05-20 14:30 UTC by rubenv

Added a separate interface to not break existing code.

2020-05-20 14:46 UTC, olivere requested changes
Can you review the comments, please?

I wouldn't care if the `CatalogSystemWriter` would be integrated into `CatalogWriter` as we didn't release v1.0 yet. So things _can_ still change.

I'd avoid `CATALOG_SYSTEM_GROUP` if I could, especially as it invites people to add products to categories via `ARTICLE_TO_CATALOGGROUP_MAP`, which in most cases will make working with BMEcat files 2-pass instead of 1-pass: First you insert the product, then you to the mapping to categories. Thank god they fixed that with `CLASSIFICATION_SYSTEM` in BMEcat 1.2.

2020-05-20 14:46 UTC, olivere commented on bmecat12/group_system.go
> +	return gs.Type == "root"
Maybe add an additional `gs != nil && ...`?

2020-05-20 14:46 UTC, olivere commented on bmecat12/group_system.go
> +	return gs.Type == "node"
Same as above: `gs != nil && ...`?

2020-05-20 14:46 UTC, olivere commented on bmecat12/group_system.go
> +	return gs.Type == "leaf"
Same as above: `gs != nil && ...`?

2020-05-20 14:46 UTC, olivere commented on bmecat12/writer.go
> +type CatalogGroupSystemWriter interface {
The name of the comment should start with the interface name, the method name etc. Something like:

```
// CatalogGroupSystemWriter, when implemented by a consumer, allows to write
// a CATALOG_GROUP_SYSTEM.
type CatalogGroupSystemWriter interface {
  ...
}
```

2020-05-20 14:55 UTC, rubenv commented
> I'd avoid `CATALOG_SYSTEM_GROUP` if I could, especially as it invites people to add products to categories via `ARTICLE_TO_CATALOGGROUP_MAP`, which in most cases will make working with BMEcat files 2-pass instead of 1-pass: First you insert the product, then you to the mapping to categories. Thank god they fixed that with `CLASSIFICATION_SYSTEM` in BMEcat 1.2.

I'm no expert on BMEcat, but that's what they use in the Mercateo samples we received.

That being said it doesn't work yet. Let me check with them if they also support `CLASSIFICATION_SYSTEM`.

2020-05-20 15:24 UTC, olivere commented
> > I'd avoid `CATALOG_SYSTEM_GROUP` if I could, especially as it invites people to add products to categories via `ARTICLE_TO_CATALOGGROUP_MAP`, which in most cases will make working with BMEcat files 2-pass instead of 1-pass: First you insert the product, then you to the mapping to categories. Thank god they fixed that with `CLASSIFICATION_SYSTEM` in BMEcat 1.2.
> 
> I'm no expert on BMEcat, but that's what they use in the Mercateo samples we received.
> 
> That being said it doesn't work yet. Let me check with them if they also support `CLASSIFICATION_SYSTEM`.

I'm pretty sure they do. It's valid BMEcat 1.2 after all.

2020-05-20 15:44 UTC, rubenv commented
Will give it a go. If that works, feel free to ignore this PR. Will let you
know.

On Wed, May 20, 2020, 17:25 Oliver Eilhard <notifications@github.com> wrote:

> I'd avoid CATALOG_SYSTEM_GROUP if I could, especially as it invites
> people to add products to categories via ARTICLE_TO_CATALOGGROUP_MAP,
> which in most cases will make working with BMEcat files 2-pass instead of
> 1-pass: First you insert the product, then you to the mapping to
> categories. Thank god they fixed that with CLASSIFICATION_SYSTEM in
> BMEcat 1.2.
>
> I'm no expert on BMEcat, but that's what they use in the Mercateo samples
> we received.
>
> That being said it doesn't work yet. Let me check with them if they also
> support CLASSIFICATION_SYSTEM.
>
> I'm pretty sure they do. It's valid BMEcat 1.2 after all.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/olivere/bmecat/pull/5#issuecomment-631545867>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAKPGH6DCRXLJD3IUNRAU3RSPY5FANCNFSM4NF7VPNA>
> .
>

2020-05-26 14:20 UTC, rubenv commented
Unfortunately it seems we need the use of group systems.

However, I don't feel like promoting outdated features. It's no problem to carry our fork forward (we won't be updating it much anyway), so I leave the choice up to you.

I can fix the PR, but you're also free to close it.

2020-05-27 10:21 UTC, olivere commented
The PR is good, it just needs some modifications. I will keep this open for the next version, and probably merge `CatalogGroupSystemWriter` into main interface (as stated in the review).

IIRC `GROUP_SYSTEM` and stuff was BMEcat 1.0, and the other way of categorization came with BMEcat 1.2. Both should be possible, but I only required the newer version.

Bear with me. I'm pretty busy now so it'll take a while.

2026-06-18 15:16 UTC, closed without merging